//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Building_Visitor_Management_System_Frola_Ndlovu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public int VisitorID { get; set; }
        public int TenantID { get; set; }
    
        public virtual Tenant Tenant { get; set; }
        public virtual Visitor Visitor { get; set; }
    }
}
